[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependencies]
torch = ">=2.0.0+cu118"
tqdm = ">=4.65.0"
visdom = ">=0.2.4"

[project]
name = "dry-torch"
version = "0.0.1"
authors = [{ name = "Nicolas Vercheval", email = "nicolas.vercheval@ugent.be" }]
description = "This package helps train, document and evaluate a Pytorch model."
keywords = ["pytorch", "training", "structured_data", "autoencoders"]
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "torch >= 2.1",
    "numpy",
    "tqdm",
    "pandas",
    "PyYAML >= 6.0",
]

[project.optional-dependencies]
plot_local = ["pyplot"]
plot_server = ["visdom"]
all = ["plotly", "visdom"]
dev = ["pytest"]

[tool.setuptools.package-data]
"dry_torch" = ["py.typed"]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://github.com/nverchev/dry_torch"
Issues = "https://github.com/nverchev/dry_torch/issues"
Changelog = "https://github.com/nverchev/dry_torch/blob/master/CHANGELOG.md"


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--import-mode=importlib", "--ignore=tests/test_plotter.py"]
log_cli = true
log_cli_level = "DEBUG"

[tool.mypy]
namespace_packages = false
files = ["src/", "tests/"]